workflows:
  version: 2
  wireguard_dns:
    jobs:
      - packer      

version: 2

jobs:
  packer:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install packer
#          command: sudo snap install packer
          command: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install packer
      - run: 
          name: Build a snapshot with packer
          command: |
            packer build packer/wireguard-dns.yaml

